<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="pnidsimulator" nsURI="http://org.pnml.tools/epnk/applications/pnids/simulator"
    nsPrefix="pnidsa">
  <eClassifiers xsi:type="ecore:EClass" name="TransitionActivationAnnotation" eSuperTypes="../../org.pnml.tools.epnk.annotations/model/NetAnnotations.ecore#//ObjectAnnotation"/>
  <eClassifiers xsi:type="ecore:EClass" name="PlaceMarkingAnnotation" eSuperTypes="../../org.pnml.tools.epnk.annotations/model/NetAnnotations.ecore#//ObjectAnnotation ../../org.pnml.tools.epnk.annotations/model/NetAnnotations.ecore#//TextualAnnotation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
</ecore:EPackage>
